Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 8080, host: 9090
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  
  config.vm.provider "virtualbox" do |v|
  v.memory = 4096
  v.cpus = 2
end

  config.vm.provision "shell", inline: <<-SHELL

    echo "===> ADD REPOSITORY FOR JENKINS"
    wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
    sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
    
    echo "===> UPDATE REPOSITORY"
    apt-get update

    echo "===> INSTALL JAVA 8"
    apt-get -y install openjdk-8-jdk

    echo "===> INSTALL GIT"
    apt-get -y install git

    echo "===> INSTALL HTTPING"
    apt-get -y install httping

    echo "===> INSTALL MAVEN"
    mkdir /home/ubuntu/distr
    cd /home/ubuntu/distr
    sudo wget http://mirror.linux-ia64.org/apache/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
    tar xvf apache-maven-3.5.0-bin.tar.gz -C /opt/
    
    export PATH=/opt/apache-maven-3.5.0/bin:$PATH
    export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
    export M3_HOME=/opt/apache-maven-3.5.0/

    echo "===> INSTALL JENKINS"
    apt-get -y install jenkins

    sudo sed -i s/HTTP_PORT=8080/HTTP_PORT=8081/g /etc/default/jenkins

    sudo systemctl start jenkins
    sudo systemctl status jenkins
  SHELL
end
