Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 8080, host: 9090
  
  config.vm.provision "shell", inline: <<-SHELL

    echo "===> INSTALL JAVA 8"
    apt-get update
    apt-get -y install openjdk-8-jdk

    echo "===> INSTALL GIT"
    apt-get -y install git

    if [ ! -d ./application/spring-petclinic/source ]; then
      mkdir application application/spring-petclinic
      cd ./application/spring-petclinic

      echo "===> CLONE PETCLINIC REPOSITORY"
      git clone https://github.com/spring-projects/spring-petclinic.git source
      cd source
    else
      cd ./application/spring-petclinic/source
    fi

    if [ ! -d ../bin ]; then
      echo "===> BUILD PETCLININC APPLICATION"
      ./mvnw clean package
      mkdir ../bin
      mv ./target/spring-petclinic-1.5.1.jar ../bin
    fi

    cd ../bin/

    echo "===> RUN PETCLINIC APPLICATION"
    nohup java -jar spring-petclinic-1.5.1.jar &
  SHELL
end
